### ISSUE TITLE
Can't instantiate abstract class ControllerApplication with abstract methods

### ISSUE THREAD

**Issue by san-av** [daniel17903/ZigCoHTTP#3]
I installed the requisite packages of 'ZigCoHTTP' on Ubuntu 20.04.6 LTS (linux kernel v5.15.x) system. The system has following python and pip versions:
 - Python v3.8.10 
 - pip v20.0.2 

When I run the 'ZigCoHTTP' app, it throws the following error:
____________________________________________________________
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    zigbee_controller = ZigbeeController()
  File "/home/sansys/src/XBee/ZigCoHTTP/zigbee_controller.py", line 15, in __init__
    self.app = ControllerApplication(self.ezsp, os.getenv('DATABASE_FILE', "devices.db"))
TypeError: Can't instantiate abstract class ControllerApplication with abstract methods add_endpoint, connect, disconnect, load_network_info, permit_ncp, permit_with_link_key, reset_network_info, send_packet, start_network, write_network_info
____________________________________________________________

**Comment by dimkaddi** [comment]
I solved the problem by changing the dependencies
\- bellows==0.7.0
\+ bellows-homeassistant

Project started on python3.8 but still can't connect to EZSP
```
Generic Zigbee Coordinator (EZSP)
Firmware: 6.10.3.0 build 297
```
